### ISSUE TITLE
malformed message packet

### ISSUE THREAD

**Issue by armoreal** [kolobok86/dns-proxy#2]
Got this error in dig responce...

> ;; Warning: query response not set
> ;; Warning: Message parser reports malformed message packet.

to fix query responce it's enough to replace QR: dnsRequest.QR,  with QR: true in localDnsResponse.
But it doesn't help with malformed message packet.

**Comment by armoreal** [comment]
Fixed with following response settings:
`localDnsResponse = {
                ID: dnsRequest.ID,
                QR: true,//dnsRequest.QR,
                Opcode: dnsRequest.Opcode,
                AA: dnsRequest.AA,
                TC: dnsRequest.TC,
                RD: dnsRequest.RD,
                RA: true,
                Z: dnsRequest.Z,
                RCODE: 0,       // dnsRequest.RCODE,    0 - no errors, look in RFC-1035 for other error conditions
                QDCOUNT: dnsRequest.QDCOUNT,
                ANCOUNT: answers.length,
                NSCOUNT: dnsRequest.NSCOUNT,
                ARCOUNT: 0,//dnsRequest.ARCOUNT,
                questions: dnsRequest.questions,
                answers: answers
            }`

**Comment by kolobok86** [comment]
Thank you @armoreal,
Checked it, seems you're right. Would you like to create PR with the fix?

**Comment by kolobok86** [comment]
Please nevermind, fixed it myself: https://github.com/kolobok86/dns-proxy/releases/tag/v0.0.2 

Thanks again!
