### ISSUE TITLE
server is not able to bind address

### ISSUE THREAD

**Issue by vadim-shadrin** [kolobok86/dns-proxy#5]
initConfig:
{
    "remoteDnsConnectionMode": "udp",
    "upstreamDnsUdpHost": "8.8.8.8",
    "upstreamDnsUdpPort": 53,
    "localDnsPort": 53,
    "forgedRequestsTTL": 10,
    "upstreamDnsTlsHost": "8.8.8.8",
    "upstreamDnsTlsPort": 853,

    "requestsToForge": [
        {
            "comment": "mariadb node m1",
            "hostName": "maria.swarm",
            "ip": "10.1.0.20"
        },
        {
            "comment": "mariadb node m2",
            "hostName": "maria.swarm",
            "ip": "10.1.0.21"
        },
        {
            "comment": "mariadb node m3",
            "hostName": "maria.swarm",
            "ip": "10.1.0.22"
        }
    ]
}

fileContents logged ^^ Wed, 18 Nov 2020 04:30:25 GMT
server error:
Error: bind EACCES 10.1.0.11:53
    at dgram.js:337:20
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by vadim-shadrin** [comment]
What version of nodejs do you use?

**Comment by vadim-shadrin** [comment]
Sorry, I forgot  than less then 1000 port for root only

**Comment by kolobok86** [comment]
Hello @vadim-shadrin ,

Thanks for reporting that, I'll mention this info in README, may save time to others.

Sorry for late reply, I didn't look into that repo for a while, and getting back to this project just now.
